"""empty message

Revision ID: c19a9202557b
Revises: 
Create Date: 2022-08-12 17:05:32.664788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c19a9202557b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('departement')
    op.drop_table('etudiant')
    op.drop_table('drivers')
    op.drop_table('person')
    op.drop_table('vehicles')
    op.drop_table('villes_france_free')
    op.drop_table('todo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='todo_pkey')
    )
    op.create_table('villes_france_free',
    sa.Column('ville_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ville_departement', sa.VARCHAR(length=3), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=False),
    sa.Column('ville_slug', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('ville_nom', sa.VARCHAR(length=45), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=False),
    sa.Column('ville_nom_simple', sa.VARCHAR(length=45), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=False),
    sa.Column('ville_nom_reel', sa.VARCHAR(length=45), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=False),
    sa.Column('ville_nom_soundex', sa.VARCHAR(length=20), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=False),
    sa.Column('ville_nom_metaphone', sa.VARCHAR(length=22), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=False),
    sa.Column('ville_code_postal', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=False),
    sa.Column('ville_commune', sa.VARCHAR(length=3), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('ville_code_commune', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('ville_arrondissement', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ville_canton', sa.VARCHAR(length=4), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('ville_amdi', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ville_population_2010', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ville_population_1999', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ville_population_2012', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ville_densite_2010', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ville_surface', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ville_longitude_deg', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('ville_latitude_deg', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('ville_longitude_grd', sa.VARCHAR(length=9), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('ville_latitude_grd', sa.VARCHAR(length=8), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('ville_longitude_dms', sa.VARCHAR(length=9), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('ville_latitude_dms', sa.VARCHAR(length=8), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('ville_zmin', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ville_zmax', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ville_id', 'ville_departement', 'ville_nom', 'ville_nom_reel', 'ville_code_commune', 'ville_code_postal', 'ville_longitude_deg', 'ville_latitude_deg', 'ville_nom_soundex', 'ville_nom_metaphone', 'ville_population_2010', 'ville_nom_simple', name='villes_france_free_pkey'),
    sa.UniqueConstraint('ville_commune', name='villes_france_free_ville_commune_key'),
    sa.UniqueConstraint('ville_slug', name='villes_france_free_ville_slug_key')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('make', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['drivers.id'], name='driver_id'),
    sa.PrimaryKeyConstraint('id', name='vehicles_pkey')
    )
    op.create_table('person',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('prenom', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='person_pkey')
    )
    op.create_table('drivers',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('nom', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('prenom', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='drivers_pkey')
    )
    op.create_table('etudiant',
    sa.Column('nom', sa.String(), autoincrement=False, nullable=True),
    sa.Column('prenom', sa.String(), autoincrement=False, nullable=True),
    sa.Column('sexe', sa.String(), autoincrement=False, nullable=True),
    sa.Column('parcours', sa.String(), autoincrement=False, nullable=True)
    )
    op.create_table('departement',
    sa.Column('departement_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('departement_code', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('departement_nom', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('departement_nom_uppercase', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('departement_slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('departement_nom_soundex', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('departement_id', 'departement_slug', 'departement_code', 'departement_nom_soundex', name='departement_pkey')
    )
    # ### end Alembic commands ###
